string = "Hello World"

# pre_define_functions
# 1. print()
print("Hello World")
# 2. type()
print(type(string))
# 3. input()
# input_var = input("Enter your name: ")
# print(input_var)
# 4. len()
print(len(string))
# 5. str()
# 6. int()
# 7. float()
# 8. bool()
# 9. list()
# 10. dict()
# 11. set()
# 12. tuple()
# 13. range()
# 14. sum()
# 15. min()
# 16. max()
# 17. sorted()
# 18. reversed()
# 19. enumerate()
# 20. zip()
# 21. map()


# slices
print(string[0])
print(string[1])
print(string[2])
print(string[3])
print(string[4])
print(string[5])
print(string[0:5])
print(string[5:10])
print(string[0:10])
print(string[-1])
print(string[:])
print(string[0:])
print(string[:5])